import { defineConfig } from "vite";
import solid from "vite-plugin-solid";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import {
  createReadStream,
  readdirSync,
  statSync,
  mkdirSync,
  copyFileSync,
  existsSync,
} from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

/**
 * Serve the shared assets that live outside `web/` (resources icons) in dev
 * via a middleware, and copy them into `dist/` on build.
 *
 * Fonts are served from `web/public/fonts/` (WOFF2 generated by
 * `scripts/build-fonts.py`) so Vite serves them natively; this middleware
 * does not touch them.
 *
 * Ship presets are now web-specific (`web/src/presets/`) - they are imported
 * via JSON modules and are NOT fetched from the shared `/ships/` folder.
 *
 * Shared source folders at the repo root:
 *   /resources   -> served at /resources
 */
const SHARED = ["resources"] as const;

function mimeOf(path: string): string {
  if (path.endsWith(".ttf")) return "font/ttf";
  if (path.endsWith(".otf")) return "font/otf";
  if (path.endsWith(".png")) return "image/png";
  if (path.endsWith(".jpg") || path.endsWith(".jpeg")) return "image/jpeg";
  if (path.endsWith(".svg")) return "image/svg+xml";
  if (path.endsWith(".json")) return "application/json";
  return "application/octet-stream";
}

function sharedAssetsPlugin() {
  return {
    name: "overdrive-shared-assets",
    configureServer(server: any) {
      server.middlewares.use((req: any, res: any, next: any) => {
        const url: string = req.url || "";
        for (const dir of SHARED) {
          const prefix = `/${dir}/`;
          if (url.startsWith(prefix)) {
            const rel = decodeURIComponent(url.slice(prefix.length).split("?")[0]);
            const filePath = resolve(repoRoot, dir, rel);
            if (!filePath.startsWith(resolve(repoRoot, dir))) {
              res.statusCode = 403;
              res.end();
              return;
            }
            try {
              const st = statSync(filePath);
              if (st.isFile()) {
                res.setHeader("Content-Type", mimeOf(filePath));
                res.setHeader("Content-Length", String(st.size));
                createReadStream(filePath).pipe(res);
                return;
              }
            } catch {
              // fall through to next middleware
            }
          }
        }
        next();
      });
    },
    closeBundle() {
      // Copy shared folders into dist/
      const dist = resolve(here, "dist");
      if (!existsSync(dist)) return;
      const copyDir = (src: string, dst: string) => {
        mkdirSync(dst, { recursive: true });
        for (const name of readdirSync(src)) {
          const s = resolve(src, name);
          const d = resolve(dst, name);
          const st = statSync(s);
          if (st.isDirectory()) copyDir(s, d);
          else if (st.isFile()) copyFileSync(s, d);
        }
      };
      for (const dir of SHARED) {
        const src = resolve(repoRoot, dir);
        if (existsSync(src)) copyDir(src, resolve(dist, dir));
      }
    },
  };
}

export default defineConfig({
  root: here,
  /** GitHub Pages: `/owner/repo/overdrive/` via env in CI; local dev uses `/`. */
  base: process.env.GITHUB_PAGES_BASE || "/",
  plugins: [solid(), sharedAssetsPlugin()],
  server: {
    fs: { allow: [repoRoot] },
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
  },
});
